import { join } from 'node:path';
import { writeFile, mkdir } from 'node:fs/promises';
import type { ScenarioExporter } from './exporter.interface.js';
import type { MimicScenario } from '../../types/fact-manifest.js';

/**
 * Exports MimicScenarios to LangSmith format:
 * - A JSON dataset file
 * - An upload script that creates the dataset via LangSmith SDK
 * - An evaluator function
 */
export class LangSmithExporter implements ScenarioExporter {
  readonly format = 'langsmith';

  async export(
    scenarios: MimicScenario[],
    outputDir: string,
  ): Promise<string[]> {
    await mkdir(outputDir, { recursive: true });
    const files: string[] = [];

    // Dataset JSON
    const examples = scenarios.map((s) => ({
      inputs: { question: s.input },
      outputs: {
        must_contain: s.expect.response_contains,
        must_exclude: s.expect.response_excludes,
        ...(s.expect.numeric_range
          ? { numeric_range: s.expect.numeric_range }
          : {}),
      },
      metadata: {
        tier: s.tier,
        source_fact: s.source_fact,
        platform: s.metadata.platform,
        name: s.name,
      },
    }));

    const datasetPath = join(outputDir, 'langsmith-dataset.json');
    await writeFile(
      datasetPath,
      JSON.stringify({ examples }, null, 2),
      'utf-8',
    );
    files.push(datasetPath);

    // Upload script
    const persona = scenarios[0]?.metadata.persona ?? 'default';
    const uploadPath = join(outputDir, 'langsmith-upload.ts');
    await writeFile(
      uploadPath,
      generateUploadScript(persona),
      'utf-8',
    );
    files.push(uploadPath);

    // Evaluator
    const evaluatorPath = join(outputDir, 'langsmith-evaluator.ts');
    await writeFile(evaluatorPath, EVALUATOR_TEMPLATE, 'utf-8');
    files.push(evaluatorPath);

    return files;
  }
}

function generateUploadScript(persona: string): string {
  return `import { Client } from "langsmith";
import { readFileSync } from "fs";

const client = new Client();
const raw = JSON.parse(readFileSync("./langsmith-dataset.json", "utf-8"));

const dataset = await client.createDataset("mimic-${persona}", {
  description: "Auto-generated by Mimic — ${persona} persona",
});

await client.createExamples({
  datasetId: dataset.id,
  inputs: raw.examples.map((e: any) => e.inputs),
  outputs: raw.examples.map((e: any) => e.outputs),
});

console.log(\`Created dataset \${dataset.id} with \${raw.examples.length} examples\`);
`;
}

const EVALUATOR_TEMPLATE = `import { EvaluationResult } from "langsmith/evaluation";

export function mimicEvaluator(run: any, example: any): EvaluationResult {
  const output: string = run.outputs?.output ?? "";
  const lower = output.toLowerCase();
  const { must_contain, must_exclude } = example.outputs;

  const missing = must_contain.filter(
    (t: string) => !lower.includes(t.toLowerCase())
  );
  const hallucinated = must_exclude.filter((t: string) =>
    lower.includes(t.toLowerCase())
  );
  const passed = missing.length === 0 && hallucinated.length === 0;

  return {
    key: "mimic_pass",
    score: passed ? 1 : 0,
    comment: passed
      ? "All assertions passed"
      : \`Missing: \${missing.join(", ")} | Hallucinated: \${hallucinated.join(", ")}\`,
  };
}
`;
