#!/usr/bin/env node
/**
 * Behavior pack codegen.
 *
 * Reads every `src/behavior/*.yaml` pack and emits a single
 * `src/generated/behavior.ts` exporting the parsed packs as a typed array.
 * This mirrors the OpenAPI codegen pattern: YAML is the human-authored source
 * of truth, and the runtime imports compiled data (no YAML parsing at runtime).
 *
 * Usage: npx tsx scripts/behavior-codegen.ts
 */

import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync } from 'node:fs';
import { resolve, dirname, basename } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadBehaviorPack } from '@mimicai/adapter-sdk';

const __dirname = dirname(fileURLToPath(import.meta.url));
const BEHAVIOR_DIR = resolve(__dirname, '../src/behavior');
const OUT_FILE = resolve(__dirname, '../src/generated/behavior.ts');

function main(): void {
  if (!existsSync(BEHAVIOR_DIR)) {
    console.log('No behavior/ directory; nothing to generate.');
    return;
  }

  const files = readdirSync(BEHAVIOR_DIR).filter((f) => f.endsWith('.yaml') || f.endsWith('.yml')).sort();
  const packs = files.map((f) => {
    const src = readFileSync(resolve(BEHAVIOR_DIR, f), 'utf-8');
    const pack = loadBehaviorPack(src);
    return { file: basename(f), pack };
  });

  const totalActions = packs.reduce((n, p) => n + p.pack.actions.length, 0);

  const header = `// AUTO-GENERATED by scripts/behavior-codegen.ts — do not edit.
// Source: src/behavior/*.yaml  (${files.length} pack(s), ${totalActions} action(s))
import type { BehaviorPack } from '@mimicai/adapter-sdk';

/** Compiled behavior packs, one per src/behavior/*.yaml file. */
export const behaviorPacks: BehaviorPack[] = ${JSON.stringify(packs.map((p) => p.pack), null, 2)} as unknown as BehaviorPack[];
`;

  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, header);
  console.log(`Generated ${OUT_FILE} from ${files.join(', ')} (${totalActions} actions).`);
}

main();
